languages:
  - cpp

- name: cpp
  production:
    exclude:
      - .*/test/.*\.cpp
      - .*/test/.*\.h
      - .*/test/.*\.hpp
    include:
      - .*/src/.*\.cpp
      - .*/src/.*\.h
      - .*/src/.*\.hpp
  test:
    include:
      - .*/test/.*\.cpp
      - .*/test/.*\.h
      - .*/test/.*\.hpp
    exclude:
      - .*/src/.*\.cpp
      - .*/src/.*\.h
      - .*/src/.*\.hpp