sudo: required

services:
    - docker

language: minimal

git:
    submodules: true

before_install:
    - docker pull debian:sid
    - docker run -e "WORKSPACE=/workspace" -e "UID=$(id -u)" -e "GID=$(id -g)"
      -v $TRAVIS_BUILD_DIR:/workspace --name vfrb -dit debian:sid bash
    - docker ps -a

install:
    - gem install coveralls-lcov

before_script:

script:
    - docker exec -it vfrb /workspace/run.sh build test -y
    - docker exec -it vfrb chown $UID:$GID -R /workspace

after_success:
    - docker stop vfrb
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} cov.info


notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
on_failure: change
