sudo: required

services:
    - docker

language: minimal

git:
    submodules: true

before_install:
    - docker pull debian:sid

install:
    - gem install coveralls-lcov

before_script:
    - docker run -e "WORKSPACE=/workspace" -v $TRAVIS_BUILD_DIR:/travis --name vfrb -dit debian:sid bash
    - docker ps -a

script:
    - docker exec -it vfrb cp -r /travis /workspace
    - docker exec -it vfrb /workspace/run.sh build test -y
    - docker exec -it vfrb cp -r /workspace/reports /travis/
    - docker exec -it vfrb chown $(id -u):$(id -g) -R /travis/reports

after_success:
    - docker stop vfrb
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} reports/cov.info

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
on_failure: change
