sudo: required

services:
    - docker

git:
    submodules: true

before_install:
    - docker pull debian:sid
    - docker run -v $TRAVIS_BUILD_DIR:/workspace --name vfrb -dit debian:sid bash
    - docker ps -a

install:

before_script:

script:
    - docker exec -it vfrb "ls -la /workspace"

after_success:


notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
on_failure: change
