language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
    - libboost1.55-dev

compiler:
    - g++-4.9

# whitelist
branches:
    only:
        - dev-2
        
git:
    submodules: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90

before_script:

script: 
    - ./install.sh
    - pushd test/build
    - make
    - popd
    - build/VFR-Test


notifications:
    email:
        recipients:
           - julian.jack@hotmail.de
        on_success: change
on_failure: change
