language: cpp

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.63-all-dev
    - libboost1.63-dev

compiler:
    - g++

# whitelist
branches:
    only:
        - dev-2
        
git:
    submodules: false

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq

install:

before_script:

script: ./install.sh

notifications:
    email:
        recipients:
           - julian.jack@hotmail.de
        on_success: always
on_failure: always
