sudo: required

services:
    - docker

language: minimal

git:
    submodules: true

before_install:
    - docker pull debian:stretch-slim

before_script:
    - docker run -e "WORKSPACE=$TRAVIS_BUILD_DIR" -e "VFRB_COMPILER=g++" -v $TRAVIS_BUILD_DIR:/travis --name vfrb -dit debian:stretch-slim bash
    - docker ps -a
    - docker exec -it vfrb sh -c "echo 'deb http://ftp.debian.org/debian stretch-backports main' >> /etc/apt/sources.list"

script:
    - docker exec -it vfrb sh -c "mkdir -p $TRAVIS_BUILD_DIR"
    - docker exec -it vfrb sh -c "cp -r /travis/. $TRAVIS_BUILD_DIR"
    - docker exec -it vfrb sh -c "$TRAVIS_BUILD_DIR/run.sh build test -y"
    - docker exec -it vfrb sh -c "cp -r $TRAVIS_BUILD_DIR/reports /travis/"
    - docker exec -it vfrb sh -c "chown $(id -u):$(id -g) -R /travis/reports"
    - docker stop vfrb

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
        on_failure: change
