sudo: required

services:
    - docker

language: minimal

git:
    submodules: true

before_install:
    - docker pull debian:sid

install:
    - gem install coveralls-lcov

before_script:
    - docker run -e "WORKSPACE=$TRAVIS_BUILD_DIR" -e "VFRB_COMPILER=g++-6" -v $TRAVIS_BUILD_DIR:/travis --name vfrb -dit debian:sid bash
    - docker ps -a

script:
    - docker exec -it vfrb mkdir -p $TRAVIS_BUILD_DIR
    - docker exec -it vfrb cp -r /travis/. $TRAVIS_BUILD_DIR
    - docker exec -it vfrb $TRAVIS_BUILD_DIR/run.sh build test -y
    - docker exec -it vfrb cp -r $TRAVIS_BUILD_DIR/reports /travis/
    - docker exec -it vfrb chown $(id -u):$(id -g) -R /travis/reports
    - docker stop vfrb

after_success:
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} reports/cov.info

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
on_failure: change
